# Generated by Django 5.1.4 on 2025-01-13 21:33
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('ordering', models.IntegerField()),
                ('link', models.URLField()),
            ],
        ),
    ]
