# Generated by Django 5.1.4 on 2025-01-15 19:10
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_1', models.CharField(max_length=15)),
                ('phone_number_2', models.CharField(max_length=15)),
                ('adderss_1', models.CharField(max_length=100)),
                ('adderss_2', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField()),
                ('our_vision', models.TextField()),
                ('our_mission', models.TextField()),
                ('meta', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('googel', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('ordering', models.IntegerField()),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
