# Generated by Django 5.1.4 on 2025-01-26 19:05
# flake8: noqa
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eg_number', models.CharField(max_length=15)),
                ('ksa_number', models.CharField(max_length=15)),
                ('eg_adderss', models.CharField(max_length=100)),
                ('ksa_adderss', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField()),
                ('our_vision', models.TextField()),
                ('our_mission', models.TextField()),
                ('student_counter', models.IntegerField()),
                ('teacher_counter', models.IntegerField()),
                ('partner_counter', models.IntegerField()),
                ('meta', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('linkedin', models.URLField(null=True)),
                ('googel', models.URLField(null=True)),
                ('footer_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('ordering', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(upload_to='media/')),
                ('ordering', models.IntegerField()),
                ('link', models.URLField(null=True)),
            ],
        ),
    ]
