# Generated by Django 5.1.4 on 2025-01-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
