# Generated by Django 5.1.4 on 2025-01-14 21:07
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_slider_description_alter_slider_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_one', models.CharField(max_length=50)),
                ('phone_number_two', models.CharField(max_length=50)),
                ('adderss_one', models.CharField(max_length=100)),
                ('adderss_two', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about_us', models.TextField()),
                ('Our_vision', models.TextField()),
                ('our_mission', models.TextField()),
            ],
        ),
    ]
