# Generated by Django 5.1.4 on 2025-01-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_configuration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='adderss_one',
            new_name='adderss_1',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='adderss_two',
            new_name='adderss_2',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='Our_vision',
            new_name='our_vision',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='phone_number_one',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='phone_number_two',
        ),
        migrations.AddField(
            model_name='configuration',
            name='googel',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='meta',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='phone_number_1',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='phone_number_2',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='twitter',
            field=models.URLField(null=True),
        ),
    ]
