# Generated by Django 5.1.4 on 2024-12-10 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_useraccount_date_joined_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Parents_mobile',
            new_name='parent_phone',
        ),
    ]
